interface nft {
	slug: string;
    name: string;
	image: string;
    info: string;
}

const data: nft[] = [
// { slug: "mutant-ape-yacht-club", name: "Mutant Ape Yacht Club", image: "mutant-ape-yacht-club.png", info: "<p>The Mutant Ape NFT collection, the most famous mutant NFT, was born in August 2021. The team behind the famous Bored Ape Yacht Club or BAYC NFTs, Yuga Labs, created the Mutant Ape Yacht Club Collection (MAYC) in pursuit of long-term goals:</p> <ul> <li>To establish an NFT-only media empire.</li> </ul> <p>On the other hand, Mutant Ape's NFTs have been an important milestone for the Bored Apes ecosystem, bringing even more attention to BAYC.</p> <p>Beyond being a collection, which we can say, has been secondary within this ecosystem, Mutant Apes has also registered promising success figures, with over $1 billion in sales in one year. Following its launch, the NFT Mutant Ape Yacht Club collection has grown dramatically to become one of the most important in the field of NFT projects used as PFP.</p>"},
// { slug: "bored-ape-yacht-club", name: "Bored Ape Yacht Club", image: "bored-ape-yacht-club.png", info: "<p>Bored Ape Yacht Club is, along with CryptoPunks, one of the most popular digital collectibles in NFT format on Ethereum. If CryptoPunks can be considered the genesis of the PFP (profile picture) concept applied to collectible digital assets that take the form of non-fungible tokens, Bored Ape Yacht Club represents the refinement of this concept through a series of innovations.</p><p>First of all, the Bored Ape Yacht Club nfts are not only presented as a digital collectible that follows the canon established by CryptoPunks -with a supply capped at 10,000 units and an attribute system linked to rarity. Rather, each Bored Ape Yacht Club NFT represents a membership token to an exclusive digital hangout called the swamp club.</p><p>The second novelty is that Bored Apes Yacht Club implements a much more generous licensing system for its IP (intellectual property), which allows owners of NFTs to exploit them commercially -for example, licensing all kinds of derivatives, editorial, and audiovisual products, or merchandising. The CryptoPunks, on the other hand, were launched under a much more restrictive IP regime, which allowed a level of exploitation by NFT holders to be capped and restricted to certain uses -although that is something that has recently changed, as a result of the acquisition of CryptoPunks and Meebits IP from Larva Labs by Yuga Labs, creators of Bored Ape Yacht Club.</p><p>In this article, we'll take a look at what Bored Ape Yacht Club are, review their origins as a collection of NFTs, explore their distinguishing features, and show you what metrics are important to consider before proceeding to purchase your first ape monkey.</p>"},
// { slug: "cryptopunks", name: "CryptoPunks", image: "cryptopunks.png", info: "<p>The CryptoPunks are one of the most representative NFT collections on Ethereum. Some consider them the genesis of non-fungible tokens as a technology, but it is a controversial issue since there are previous projects in Ethereum and even in other blockchains -colored coins in Bitcoin and proto-NFT in Counterparty.</p><p>What is certain is that CryptoPunks invented the concept of PFP (profile picture) as a collectible digital item. A concept linked to a series of characteristics that CryptoPunks would turn into a kind of canon (many collections also adopt a supply of 10,000 avatar units and an attribute system linked to rarity similar to that of cryptopunks). So while we can't consider them the first Ethereum NFT, CryptoPunks are certainly one of the earliest examples of this technology, and one that has had the most impact.</p><p>In this guide we will not only explain what CryptoPunks are, we will also review their history, analyze the attributes that differentiate them and teach you what are the most relevant metrics that you have to analyze before launching to buy an NFT.</p>"},
// { slug: "otherdeed", name: "Otherdeed for Otherside", image: "otherdeed.png", info: "<p>There are only a few projects as bullish about the concept of metaverse as Bored Ape Yacht Club. They initially put their lore at the forefront and, out of nowhere, launched a YouTube video revealing their Otherside ape project. Soon after, the Otherdeed NFT project was dropped. This project aims to create a metaverse where most NFT-based projects have a voice.</p>"},
// { slug: "azuki", name: "Azuki", image: "azuki.png", info: "<p>Unique hand-drawn artworks were the first creations to be tokenized within the blockchain. But that was soon taken over by the pixelated collectibles. Azuki is an NFT project that focuses on bringing back the old days when hand-drawn artworks ruled the crypto space. And it has been successful for the most part.</p>"},
// { slug: "proof-moonbirds", name: "Moonbirds", image: "proof-moonbirds.png", info: "<p>If we want to answer what are the Moonbirds, we have an straightforward answer, they are a group of owls that live on the Ethereum blockchain. But, we need to provide more details, so we can say that the Moonbirds NFT are a series of 10,000 digital assets, each depicting a unique owl avatar, which can be characterized by features like mohawks, eye patches, and blazing eyes. They're part of the trend of using unique profile pictures (PFPs) on social media, which has taken the cryptocurrency industry by storm.</p> <p>Owning a Moonbird grants access to the PROOF Collective, a private club for members to reap additional benefits. Each Moonbird is a one-of-a-kind NFT, meaning that although they share some similarities, no two are exactly alike.</p> <p>The initial release of NFT Moonbirds was limited to 7,875 NFTs, which sold out within 48 hours of release due to limited availability. This led to concern from the NFT community about accessibility issues. Kevin Rose, an American internet entrepreneur, created the Moonbirds NFT collection as part of his Proof Collective in 2022. The full supply was divided into three groups: 2,000 were reserved for members, 7,875 were released to the public via a whitelist, and the final 125 were held by the collective administrators for future use. The Moonbirds NFT price, has taken the environment by surprised.</p>"},
// { slug: "bored-ape-kennel-club", name: "Bored Ape Kennel Club", image: "bored-ape-kennel-club.png", info: "<p>Bored Ape Kennel Club consists of 10,000 programmatically generated dog NFTs with 170 possible traits. Initially launched by the Bored Ape Yacht Club developers for the Ape owners in 2021, NFT enthusiasts can now find these dogs floating around in several marketplaces.</p><p>Taking cues from its forefathers, the Bored Ape Yacht Club dropped these programmatically generated puppies on their official platform for free. Meant as companions for the original Bored Ape troupe, these NFTs soon hit their stride and took the NFT world by storm, reinforcing the precedent other successful PFP projects set.</p><p>And it is done all for the sake of giving back to the community, because as we said, BAYC holders had free access to the Bored Ape Kennel Club airdrop (they only had to pay for the minting transaction gas fee).</p><p>Each generated four-legged mammal has unique traits ranging from armors to collars to even the type of asset between their teeth. So, it should not be an understatement stating these pups have a lot of value to go along with their cuteness. And considering they were free when they initially dropped, they can be a sign of opportunity within the NFT space that would make it more appealing to those still yet to enter this domain.</p>"},
// { slug: "doodles", name: "Doodles", image: "doodles.png", info: "<p>The Doodles NFT, is a unique and dynamic collection of 10,000 non-fungible tokens that have been minted on the Ethereum blockchain. With a vibrant and community-driven collection of avatars has a vast array of potential facial expressions, hairstyles, hats, bodies, and other traits that express the diversity and uniqueness of the collection. With its seemingly endless possibilities, it is no wonder that the Doodles NFTs have become a popular choice for profile pictures on social media platforms, as well as in the online NFT community.</p><p>The collection was created by the talented artist Burnt Toast and is known for its wide array of diverse characters, each with its own quirky personality and style. This vast array of traits and combinations makes it easy for anyone to find a Doodle NFT that appeals to them and their unique interests. Additionally, owners of Doodles NFTs have the opportunity to participate in the Doodles community treasury, known as the Doodlebank, which funds the expansion and growth of the project through community experiences, collaborations, and philanthropic ventures.</p><p>The artists behind the Doodles NFT collection are Evan Keast, Scott Martin, and Jordan Castro. They use working aliases, Tulip, Burnt Toast, and Poopie, respectively. Before the launch of the Doodles NFT collection, Keast and Castro were already well-known in the NFT community, having helped launch the legendary NFT project CryptoKitties in 2017. Meanwhile, Martin had been minting his own pieces and growing his creative brand in the NFT space for about a year. The Doodles NFTs feature original artwork created by Martin, with hundreds of unique visual traits randomly generated to create the collection.</p><p>The Doodles NFT collection is a visually stunning array of cartoon characters with bright pastel color combinations, each with its own unique set of traits that includes hair, piercings, face, head, background, and body. The rarity levels of the Doodles NFTs are determined by the rarity of the traits, with some traits being rarer than others. For example, bubblegum face, devil cat, and holographic alien are considered to be rare traits.</p><p>Overall, the Doodles NFT is a remarkable and impactful project that continues to captivate the NFT community. The collection's release was met with great enthusiasm, with the NFTs selling out in minutes during the exclusive pre-sale. The project's direction is determined by the fair voting of NFT holders, with several airdrops and projects having been approved by the community since its release. Whether you are an NFT collector, a fan of colorful art, or just someone looking for a unique profile picture, the Doodles NFT is definitely worth exploring.</p>"},
// { slug: "clonex", name: "Clone X", image: "clonex.png", info: "<p>While there are many NFT projects headed to the metaverse, none of them holds a candle to the iterations developed in the Clone X -Takashi Murakami project. It is spearheading toward the metaverse with high-end NFT avatars that are designed within a 3d ecosystem.</p>"},
// { slug: "otherside-koda", name: "Otherside Koda", image: "otherside-koda.png", info: "Otherside Koda 是一个由 创建的NFT藏品, 于2023-4-5发布。该项目包含 4,807 个在以太坊区块链上的独特电子物品。我们将它分类为 pfp/头像 项目 且它是 Yuga Labs 主要收藏的一部分."},
{"slug": "cryptopunks", "name": "CryptoPunks", "image": "cryptopunks.png", "info": "One of the earliest and most iconic NFT projects, Cryptopunks are 8-bit style pixel art characters with unique attributes and traits that were randomly generated and minted on the Ethereum blockchain in 2017. They are now considered a valuable collector's item."},
{"slug": "bored-ape-yacht-club", "name": "Bored Ape Yacht Club", "image": "bored-ape-yacht-club.png", "info": "A community-driven NFT project featuring a variety of whimsical, cartoon-style apes with unique outfits and accessories. Members of the Bored Ape Yacht Club community gain access to exclusive events and perks."},
{"slug": "mutant-ape-yacht-club", "name": "Mutant Ape Yacht Club", "image": "mutant-ape-yacht-club.png", "info": "A spinoff of the Bored Ape Yacht Club, Mutant Ape Yacht Club features mutated apes with even more unique and rare attributes."},
{"slug": "azuki", "name": "Azuki", "image": "azuki.png", "info": "A Japanese-themed collection of NFTs featuring cute, chibi-style characters with unique expressions and accessories."},
{"slug": "degods", "name": "DeGods", "image": "degods.png", "info": "A collection of mythological and fantasy-inspired characters with unique, hand-drawn designs. Some Degods come with special powers and abilities."},
{"slug": "otherdeed", "name": "Otherdeed for Otherside", "image": "otherdeed.png", "info": "A collection of abstract, geometric NFTs with intricate designs."},
{"slug": "thecaptainz", "name": "The Captainz", "image": "thecaptainz.png", "info": "A collection of cartoon-style characters with unique attributes and accessories, inspired by pirate and nautical themes."},
{"slug": "the_sandbox", "name": "The Sandbox", "image": "the_sandbox.png", "info": "A virtual world powered by blockchain technology, where players can build, create and monetize their own gaming experiences. NFTs are used to represent virtual land, items, and other assets within the game."},
{"slug": "clonex", "name": "Clone X", "image": "clonex.png","info": "A project inspired by Cryptopunks, featuring similar style pixel art characters with unique attributes that are randomly generated and minted on the Ethereum blockchain."},
{"slug": "Decentraland", "name": "Decentraland", "image": "Decentraland.png", "info": "Another virtual world powered by blockchain technology, where players can buy, sell and trade virtual land, items, and experiences. NFTs are used to represent these assets within the game."},
];
export default data;